export interface Attendance {
  id?: string; // Optional as it will be generated by the DB
  employeeId: string;
  date: string; // ISO Date string
  status: 'present' | 'absent' | 'on_leave';
  checkInTime?: string | null;  // ISO DateTime string
  checkOutTime?: string | null; // ISO DateTime string
  createdAt?: Date;
  updatedAt?: Date;
}
