export interface Leave {
  id?: string; // Optional as it will be generated by the DB
  employeeId: string;
  startDate: string; // ISO Date string
  endDate: string;   // ISO Date string
  reason: string;
  status: 'pending' | 'approved' | 'rejected';
  approverId?: string | null; // User ID of the approver
  createdAt?: Date;
  updatedAt?: Date;
}
