export interface User {
  id?: string; // Optional as it will be generated by the DB
  name: string;
  email: string;
  password?: string; // Optional for responses, required for creation
  role: 'admin' | 'hr' | 'employee';
  departmentId?: string | null;
  phone?: string | null;
  address?: string | null;
  profileImage?: string | null;
  createdAt?: Date;
  updatedAt?: Date;
}
